[package]
name = "ixc_schema"
edition = "2021"
readme = "README.md"
version.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ixc_message_api = { path = "../message_api" }
simple_time = { path = "../util/simple_time" }

[features]
default = ["address", "std"]
address = []
std = []
