[package]
name = "interchain_schema"
edition = "2021"
version.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
interchain_message_api = { path = "../message_api" }
interchain_schema_macros = { path = "../schema_macros" }

[features]
default = ["address", "macros"]
address = []
macros = []
