[package]
name = "example_bank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeropb = {path = "../zeropb"}
#cosmossdk_core = {dir = "../cosmossdk_core"}
