[package]
name = "simple_time"
edition = "2021"
description = "A simple time i128 nano-second precision time library"
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]

[lints]
workspace = true

[features]
default = ["std"]
std = []