[package]
name = "cosmossdk_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
num_enum = { version = "0.7.1", default-features = false }
lol_alloc = "0.4.0"
tonic = { version = "0.10.2", optional = true }
#zeropb = { path = "../zeropb" }

[features]
default = []
tonic = ["dep:tonic"]

[build-dependencies]
cbindgen = "0.26.0"
