[package]
name = "ixc_testing"
edition = "2021"
description = "Interchain SDK Testing"
readme = "README.md"
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ixc_core = { path = "../core" }
ixc_message_api = { path = "../message_api" }

[lints]
workspace = true
