[workspace]
members = [
    "core",
    "core_macros",
    "state_objects",
    "state_objects_macros",
    "schema",
    "schema_macros",
    "message_api",
    "testing",
    "util/simple_time",
    "codecs/proto", "codecs/evm",
    "vm/wasmtime", "vm/api", "vm/hypervisor",
]

[workspace.package]
repository = "https://github.com/cosmos/cosmos-sdk"
license = "Apache-2.0"

[workspace.lints]

[workspace.lints.rust]
missing_docs = "deny"

[package]
name = "ixc"
edition = "2021"
description = "Interchain SDK"
readme = "README.md"
version = "0.0.2"
repository.workspace = true
license.workspace = true

[dependencies]
ixc_core = { path = "core", version = "0.0.2" }
ixc_schema = { path = "schema", version = "0.0.2" }
ixc_message_api = { path = "message_api", version = "0.0.2" }
state_objects = { path = "state_objects", version = "0.0.2" }
simple_time = { path = "util/simple_time", version = "0.0.1" }
ixc_core_macros = { path = "core_macros", version = "0.0.2" }
ixc_schema_macros = { path = "schema_macros", version = "0.0.2" }
state_objects_macros = { path = "state_objects_macros", version = "0.0.2" }

[dev-dependencies]
ixc_testing = { path = "testing", version = "0.0.2" }
arrayvec = "0.7.6"
thiserror = "1.0.63"

[lints]
workspace = true

[features]
default = ["core_macros", "schema_macros", "state_objects_macros"]
core_macros = []
schema_macros = []
state_objects_macros = []
