[workspace]
members = [
    "core",
    "core_macros",
    "state_objects",
    "schema",
    "schema_macros",
    "message_api",
    "sdk_testing",
    "util/simple_time"
]

[workspace.package]
version = "0.0.1"
repository = "https://github.com/cosmos/cosmos-sdk"
license = "Apache-2.0"

[workspace.lints]

[workspace.lints.rust]
missing_docs = "deny"

[package]
name = "interchain_sdk"
edition = "2021"
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
interchain_core = { path = "core" }
state_objects = { path = "state_objects" }
simple_time = { path = "util/simple_time" }

[dev-dependencies]
interchain_sdk_testing = { path = "sdk_testing" }
arrayvec = "0.7.6"
thiserror = "1.0.63"

[lints]
workspace = true
