[workspace]
members = [
    "prelude",
    "core",
    "core_macros",
    "message_api",
    "schema",
    "state_objects"
, "schema_macros"]

[workspace.package]
version = "0.0.1"
repository = "https://github.com/cosmos/cosmos-sdk"
license = "Apache-2.0"

[workspace.lints]

[workspace.lints.rust]
missing_docs = "deny"

# The settings below are for this root package which mainly contains examples:
[package]
name = "interchain_sdk_rust"
edition = "2021"
publish = false

[lib]
path = "examples.rs"

[dependencies]
interchain_prelude = { path = "prelude" }
arrayvec = "0.7.6"
