[workspace]
members = [ "context",
    "core",
    "core_macros", "message_api",
    "prelude"
, "schema", "state_objects"]
resolver = "2"

[workspace.package]
version = "0.0.1"
repository = "https://github.com/cosmos/cosmos-sdk"
license = "Apache-2.0"

[workspace.lints]

[workspace.lints.rust]
missing_docs = "deny"
