[workspace]
members = [
    "core",
    "core_macros",
    "message_api",
    "schema",
    "state_objects"
, "schema_macros", "util/simple_time"]

[workspace.package]
version = "0.0.1"
repository = "https://github.com/cosmos/cosmos-sdk"
license = "Apache-2.0"

[workspace.lints]

[workspace.lints.rust]
missing_docs = "deny"

# The settings below are for this root package which mainly contains examples:
[package]
name = "interchain_sdk"
edition = "2021"
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
interchain_core = { path = "core" }
state_objects = { path = "state_objects" }

[dev-dependencies]
arrayvec = "0.7.6"

[lints]
workspace = true
