[package]
name = "interchain_core_macros"
edition = "2021"
version.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
