[package]
name = "state_objects"
edition = "2021"
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
interchain_core = { path = "../core" }
interchain_schema = { path = "../schema" }
simple_time = { path = "../util/simple_time" }

[lints]
workspace = true
