[package]
name = "interchain_core"
edition = "2021"
version.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
interchain_message_api = { path = "../message_api" }
interchain_schema = { path = "../schema" }

[features]
default = ["std"]
std = []