[package]
name = "ixc_core"
edition = "2021"
description = "Interchain SDK Core"
version.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ixc_message_api = { path = "../message_api" }
ixc_schema = { path = "../schema" }

[features]
default = ["std"]
std = []