[package]
name = "ixc_core"
edition = "2021"
description = "Interchain SDK Core"
version = "0.0.2"
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ixc_message_api = { path = "../message_api", version = "0.0.2" }
ixc_schema = { path = "../schema", version = "0.0.2" }
bump-scope = "0.9.1"

[features]
default = ["std"]
std = []